/**
 * ✅ EDITABLE FILE - AI Can Modify Values Here
 * 
 * Category Configuration Content
 * This file contains all category definitions for the site
 * 
 * AUTO-GENERATED by Site Builder Template Generator
 * Generated: 2025-12-11T18:00:57.395Z
 */

import type { Category } from './categories.schema'

/**
 * Blog categories with nested subcategories
 * Auto-populated from brand database (BrandCategory table)
 */
export const categories: Category[] = [
  {
    id: "e7b83bd5-de6b-44e2-97e9-33369739f711",
    name: "Product Reviews",
    slug: "product-reviews",
    showInHeader: true,
    showInFooter: true,
    subcategories: [
      {
        id: "49b41d81-3a4c-43ee-be12-c425fd01434c",
        name: "Bags",
        slug: "bags",
        showInHeader: true,
        showInFooter: true
      },
      {
        id: "8463792c-b951-4f8e-9e94-470dbccc1d1b",
        name: "Wallets",
        slug: "wallets",
        showInHeader: true,
        showInFooter: true
      },
      {
        id: "6e0d1a78-fc00-421e-8c6d-f778840b8491",
        name: "Accessories",
        slug: "accessories",
        showInHeader: true,
        showInFooter: true
      },
      {
        id: "60c1c6b3-1477-4e6e-b794-a00f0c702f03",
        name: "Travel Gear",
        slug: "travel-gear",
        showInHeader: true,
        showInFooter: true
      },
      {
        id: "cde20be2-bef7-48e3-aad9-f2c50d2539fc",
        name: "Outdoor Equipment",
        slug: "outdoor-equipment",
        showInHeader: true,
        showInFooter: true
      }
    ]
  },
  {
    id: "5f73c368-48e4-499c-9c7c-dda1ae88f213",
    name: "Brand Spotlights",
    slug: "brand-spotlights",
    showInHeader: true,
    showInFooter: true,
    subcategories: [
      {
        id: "160cc5a0-16c0-411c-b193-77afd586a604",
        name: "Interviews",
        slug: "interviews",
        showInHeader: true,
        showInFooter: true
      },
      {
        id: "7d506e70-dc0f-4eb9-874b-7172f03a1c46",
        name: "Collaborations",
        slug: "collaborations",
        showInHeader: true,
        showInFooter: true
      },
      {
        id: "27e865b3-acec-4a00-a693-46692188ff65",
        name: "New Contributors",
        slug: "new-contributors",
        showInHeader: true,
        showInFooter: true
      },
      {
        id: "16538994-beb6-4760-9bb3-b127ef2d7333",
        name: "Community Features",
        slug: "community-features",
        showInHeader: true,
        showInFooter: true
      }
    ]
  },
  {
    id: "1dc0f4a0-c327-4414-9052-c364e23f02d6",
    name: "Carry Awards",
    slug: "carry-awards",
    showInHeader: true,
    showInFooter: true,
    subcategories: [
      {
        id: "882261cd-61b0-4104-b2d0-a65bb6bfea8f",
        name: "Nominations",
        slug: "nominations",
        showInHeader: true,
        showInFooter: true
      },
      {
        id: "f1ed631c-68c4-4e5e-81ac-a17dbbb5c893",
        name: "Winners",
        slug: "winners",
        showInHeader: true,
        showInFooter: true
      },
      {
        id: "e4835938-9284-4c1b-a822-2c168254b340",
        name: "Past Awards",
        slug: "past-awards",
        showInHeader: true,
        showInFooter: true
      },
      {
        id: "62886aec-d93b-4985-854f-f6496136b7ca",
        name: "Special Mentions",
        slug: "special-mentions",
        showInHeader: true,
        showInFooter: true
      }
    ]
  },
  {
    id: "51ab769f-df2e-437a-a6f9-dfc777db098d",
    name: "Carry Guides",
    slug: "carry-guides",
    showInHeader: true,
    showInFooter: true,
    subcategories: [
      {
        id: "c8fd70d5-58a6-4071-8716-e7799b54a480",
        name: "How-To Guides",
        slug: "how-to-guides",
        showInHeader: true,
        showInFooter: true
      },
      {
        id: "8d76543d-4507-4594-8679-242a034f1730",
        name: "Carry Hacks",
        slug: "carry-hacks",
        showInHeader: true,
        showInFooter: true
      },
      {
        id: "54cc1b5b-7d19-4c05-b493-5d3021ae95a3",
        name: "Travel Tips",
        slug: "travel-tips",
        showInHeader: true,
        showInFooter: true
      },
      {
        id: "15c3a317-eef5-49a2-885f-05751035d658",
        name: "Gear Maintenance",
        slug: "gear-maintenance",
        showInHeader: true,
        showInFooter: true
      }
    ]
  }
]
