/**
 * ✅ EDITABLE FILE - AI Can Modify Values Here
 * 
 * Site Configuration Content
 * This file contains all customizable values for the site
 * 
 * AUTO-GENERATED by Site Builder Template Generator
 * Brand: Gear Haven
 * Generated: 2025-12-11T18:00:57.395Z
 */

import type { SiteConfigSchema, ColorConfigSchema } from './config.schema'

/**
 * Main site configuration
 * Values auto-populated from brand database
 */
export const siteContent: SiteConfigSchema = {
  // Brand identity
  brand: {
    id: "8ea291c0-aae9-4ea1-904b-c561ca0b0c33",
    name: "Gear Haven",
    description: "Gear Haven curates expert reviews, insightful interviews, and vibrant community stories to elevate your everyday carry experience.",
    url: "https://gear-haven-blog.vercel.app",
    logoPath: "/logo.jpg",
    faviconPath: "/logo.jpg",
    ogImagePath: "/logo.jpg",
    mainAppUrl: "https://app.thefaceless.ai",
    legalEmail: "support@banedigital.com",
    privacyEmail: "support@banedigital.com",
    tagline: "Elevate your adventures with expert tips and stylish gear insights"
  },

  // Homepage hero section
  hero: {
    title: "Welcome to Gear Haven",
    subtitle: "Elevate your adventures with expert tips and stylish gear insights"
  },

  // Default author information
  author: {
    name: "Gear Haven Team",
    bio: "Gear Haven curates expert reviews, insightful interviews, and vibrant community stories to elevate your everyday carry experience.",
    role: "Content Creator",
    image: "/logo.jpg"
  },

  // Section headings throughout the site
  sections: {
    topArticles: {
      title: "Featured Articles",
      description: "Handpicked posts just for you"
    },
    recentPosts: {
      title: "Latest Posts"
    },
    categories: {
      title: "Explore Outdoor & Travel Accessories Topics"
    }
  },

  // Newsletter subscription section
  newsletter: {
    title: "Stay Updated",
    description: "Get the latest from Gear Haven delivered to your inbox",
    disclaimer: "Unsubscribe anytime. We respect your privacy."
  },

  // Blog categories (from brand database)
  categories: [
    { 
      name: "How-To Guides",
      icon: "BookOpen",
      slug: "how-to-guides"
    },
    { 
      name: "Nominations",
      icon: "FileText",
      slug: "nominations"
    },
    { 
      name: "Bags",
      icon: "FileText",
      slug: "bags"
    },
    { 
      name: "Product Reviews",
      icon: "Shield",
      slug: "product-reviews"
    },
    { 
      name: "Interviews",
      icon: "FileText",
      slug: "interviews"
    },
    { 
      name: "Collaborations",
      icon: "FileText",
      slug: "collaborations"
    }
  ],

  // All authors for this brand (with AI-generated portraits)
  authors: [
    {
      id: "c8b66575-d9a3-44ab-82bb-88478176b587",
      name: "Chloe Tan",
      bio: "Chloe is the heart and soul of Gear Haven's community features, known for her warm and conversational writing style. With her background in journalism, she excels at conducting insightful interviews and crafting stories that resonate with readers. Her pieces often spotlight diverse voices within the carry community, fostering a sense of belonging and shared passion among readers.",
      image: "/authors/c8b66575-d9a3-44ab-82bb-88478176b587.jpg",
      role: "Community Engagement Specialist"
    },
    {
      id: "4645f2a8-ce43-43fc-93f9-660fb2d9d27a",
      name: "Marcus Alvarez",
      bio: "Marcus brings a vibrant and dynamic voice to Gear Haven, with a knack for capturing the essence of carry culture. His articles often weave personal anecdotes with broader trends, offering readers a relatable and immersive experience. With a background in anthropology, Marcus explores the cultural significance of carry gear, highlighting its impact on personal identity and community connection.",
      image: "/authors/4645f2a8-ce43-43fc-93f9-660fb2d9d27a.jpg",
      role: "Lifestyle and Culture Editor"
    },
    {
      id: "7b4db951-ff99-45f0-a922-4482df2893a2",
      name: "Samantha Reed",
      bio: "Samantha combines technical expertise with a passion for storytelling, making her reviews both informative and engaging. With a background in industrial design, she dissects every detail of carry gear, providing readers with a thorough understanding of product functionality and innovation. Her writing is precise yet approachable, reflecting her commitment to enriching the everyday carry experience.",
      image: "/authors/7b4db951-ff99-45f0-a922-4482df2893a2.jpg",
      role: "Senior Gear Analyst"
    }
  ]
}

/**
 * Color configuration
 * Brand colors in oklch() format for consistent rendering
 * Auto-converted from brand hex colors
 */
export const colorContent: ColorConfigSchema = {
  // Light mode colors
  light: {
    primary: "#2563EB",      // #2563EB
    secondary: "#64748B",  // #64748B
    accent: "#F59E0B"         // #F59E0B
  },

  // Dark mode colors (auto-lightened for contrast)
  dark: {
    primary: "#2563EB",
    secondary: "#64748B",
    accent: "#F59E0B"
  }
}
